on:
  push:
  pull_request:
  release:

jobs:
  multi-platform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm/v6
  
  single_plaform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
