on:
  push:
  pull_request:
  release:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm/v6
